### ISSUE TITLE
About En_Link_Puppet_N0

### ISSUE THREAD

**Issue by LuigiXHero** [hylian-modding/OotModLoader#10]
Is the asm code openly available? If not can that be added to the folder that would be very helpful. Trying to figure out how to draw multiple links is hard.

**Comment by denoflionsx** [comment]
I don't have the source. Only Ideka does and he just says decompile it yourself. Sorry man. =/

**Comment by denoflionsx** [comment]
Best I can do is this disassembly glank did when I was trying to understand it to fix a crash. I didn't get very far, but maybe it'll help you somehow.

[En_Link_Puppet_N0.nonovl.txt](https://github.com/hylian-modding/OotModLoader/files/3358832/En_Link_Puppet_N0.nonovl.txt)
