### ISSUE TITLE
Resolution scaling issue

### ISSUE THREAD

**Issue by RetroWolf92** [hylian-modding/OotModLoader#13]
I set my custom resolution as (Width=1920,Height=1080) in the Plugins menu, but when I exit and restart the emulator it sets my resolution as 2880x2160. I wouldn't have an issue with this were it not for the fact that apparently that high of a resolution is a massive drain on performance. 

But this begs the question:
Why does the emulator not seem to natively support widescreen resolutions?
And why does it only support as high as DX9?
Can I use other video plugins besides the ones that the modloader comes with?

**Comment by RetroWolf92** [comment]
Other than that the system runs just fine.

**Comment by Drahsid** [comment]
This program is deprecated, and Den forgot to archive the repository after a hotfix. This issue will not be resolved officially. Check out the successor to this, [Modloader64](https://github.com/hylian-modding/ModLoader64).
