### ISSUE TITLE
wording

### ISSUE THREAD

**Issue by Stannic1** [hylian-modding/OotModLoader#4]
"Team OotO nor its Discord will provide you with any information as to how to obtain this."

might wanna change it to not provide

UNLESS YOU GUYS REALLY WANT TO GIVE FREE COPIES :D

**Comment by Drahsid** [comment]
It might be better to push a commit with a separate suggested text than to submit an issue.

**Comment by denoflionsx** [comment]
It says 'nor'. As in a negative. We nor the discord will do the thing.
